basePath: /v1
host: api.example.com
info:
  contact: {}
  description: This is a sample API
  title: My API
  version: 1.0.0
paths:
  /messages/{message_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 消息 ID
        in: path
        name: message_id
        required: true
        type: string
      - description: 消息 Name
        in: path
        name: message_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      tags:
      - ken tag
swagger: "2.0"
