// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryClient interface {
	// 后续可以考虑给每个库存添加id(同一个id则增加库存量,否则根据地址创建),address(地址)
	CreateStock(ctx context.Context, in *CreateInventoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetStock(ctx context.Context, in *SetInventoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetStockInfo(ctx context.Context, in *InventoryInfoReq, opts ...grpc.CallOption) (*InventoryInfoRes, error)
	DecrStock(ctx context.Context, in *UpdateStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IncrStock(ctx context.Context, in *UpdateStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RebackStock(ctx context.Context, in *RebackStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) CreateStock(ctx context.Context, in *CreateInventoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Inventory/CreateStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) SetStock(ctx context.Context, in *SetInventoryReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Inventory/SetStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetStockInfo(ctx context.Context, in *InventoryInfoReq, opts ...grpc.CallOption) (*InventoryInfoRes, error) {
	out := new(InventoryInfoRes)
	err := c.cc.Invoke(ctx, "/Inventory/GetStockInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) DecrStock(ctx context.Context, in *UpdateStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Inventory/DecrStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) IncrStock(ctx context.Context, in *UpdateStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Inventory/IncrStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) RebackStock(ctx context.Context, in *RebackStockReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Inventory/RebackStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
// All implementations must embed UnimplementedInventoryServer
// for forward compatibility
type InventoryServer interface {
	// 后续可以考虑给每个库存添加id(同一个id则增加库存量,否则根据地址创建),address(地址)
	CreateStock(context.Context, *CreateInventoryReq) (*emptypb.Empty, error)
	SetStock(context.Context, *SetInventoryReq) (*emptypb.Empty, error)
	GetStockInfo(context.Context, *InventoryInfoReq) (*InventoryInfoRes, error)
	DecrStock(context.Context, *UpdateStockReq) (*emptypb.Empty, error)
	IncrStock(context.Context, *UpdateStockReq) (*emptypb.Empty, error)
	RebackStock(context.Context, *RebackStockReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedInventoryServer()
}

// UnimplementedInventoryServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServer struct {
}

func (UnimplementedInventoryServer) CreateStock(context.Context, *CreateInventoryReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStock not implemented")
}
func (UnimplementedInventoryServer) SetStock(context.Context, *SetInventoryReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStock not implemented")
}
func (UnimplementedInventoryServer) GetStockInfo(context.Context, *InventoryInfoReq) (*InventoryInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockInfo not implemented")
}
func (UnimplementedInventoryServer) DecrStock(context.Context, *UpdateStockReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrStock not implemented")
}
func (UnimplementedInventoryServer) IncrStock(context.Context, *UpdateStockReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrStock not implemented")
}
func (UnimplementedInventoryServer) RebackStock(context.Context, *RebackStockReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebackStock not implemented")
}
func (UnimplementedInventoryServer) mustEmbedUnimplementedInventoryServer() {}

// UnsafeInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServer will
// result in compilation errors.
type UnsafeInventoryServer interface {
	mustEmbedUnimplementedInventoryServer()
}

func RegisterInventoryServer(s *grpc.Server, srv InventoryServer) {
	s.RegisterService(&_Inventory_serviceDesc, srv)
}

func _Inventory_CreateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).CreateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/CreateStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).CreateStock(ctx, req.(*CreateInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_SetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).SetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/SetStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).SetStock(ctx, req.(*SetInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetStockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetStockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/GetStockInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetStockInfo(ctx, req.(*InventoryInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_DecrStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).DecrStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/DecrStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).DecrStock(ctx, req.(*UpdateStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_IncrStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).IncrStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/IncrStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).IncrStock(ctx, req.(*UpdateStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_RebackStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebackStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).RebackStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/RebackStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).RebackStock(ctx, req.(*RebackStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inventory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStock",
			Handler:    _Inventory_CreateStock_Handler,
		},
		{
			MethodName: "SetStock",
			Handler:    _Inventory_SetStock_Handler,
		},
		{
			MethodName: "GetStockInfo",
			Handler:    _Inventory_GetStockInfo_Handler,
		},
		{
			MethodName: "DecrStock",
			Handler:    _Inventory_DecrStock_Handler,
		},
		{
			MethodName: "IncrStock",
			Handler:    _Inventory_IncrStock_Handler,
		},
		{
			MethodName: "RebackStock",
			Handler:    _Inventory_RebackStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
